stages:
  - test
  - build
  - deploy

api unit:
  stage: test
  image: node:12
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - Backend/node_modules
  services:
    - mongo
  before_script:
    - cd Backend
    - npm install
    - cd ..
  script:
    - cd Backend
    - npm run test:ci
    - cd ..
  only:
    - master

build api:
  stage: build
  image: registry.gitlab.com/ufsec/clubfinity/build-push:latest
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $GCLOUD_SERVICE_KEY > /gcloud-service-key.json
    - cat /gcloud-service-key.json
    - /google-cloud-sdk/bin/gcloud auth activate-service-account --key-file /gcloud-service-key.json
    - docker login -u _json_key --password-stdin https://us.gcr.io < /gcloud-service-key.json
  script:
    - docker build Backend/ -t gcr.io/$PROJECT_ID/clubfinity-api
    - /google-cloud-sdk/bin/gcloud docker -- docker push gcr.io/$PROJECT_ID/clubfinity-api

deploy api:
  stage: deploy
  script:
    - echo "It works!"
