stages:
  - test
  - build
  - deploy

api unit:
  stage: test
  image: node:12
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - Backend/node_modules
  services:
    - mongo
  before_script:
    - cd Backend
    - npm install
    - cd ..
  script:
    - cd Backend
    - npm run test:ci
    - npm run lint
    - cd ..
  only:
    - master
    - merge_requests

build api:
  services:
    - docker:dind
  stage: build
  image: registry.gitlab.com/ufsec/clubfinity/build-push:latest
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $GCLOUD_SERVICE_KEY > /gcloud-service-key.json
    - cat /gcloud-service-key.json
    - /google-cloud-sdk/bin/gcloud auth activate-service-account --key-file /gcloud-service-key.json
    - docker login -u _json_key --password-stdin https://us.gcr.io < /gcloud-service-key.json
  script:
    - docker build Backend/ -t "gcr.io/$PROJECT_ID/clubfinity-api"
    - /google-cloud-sdk/bin/gcloud docker -- push "gcr.io/$PROJECT_ID/clubfinity-api"
  only:
    - master

deploy frontend:
  image: 'patwoz/expo-cli:3'
  stage: deploy
  script:
    - cd Frontend
    - npm install
    - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - expo publish
  only:
    - master

deploy api:
  image: 'google/cloud-sdk'
  stage: deploy
  script:
    - apt-get install -y gettext
    - echo $API_IMAGE_TAG
    - echo $GCLOUD_SERVICE_KEY > /gcloud-service-key.json
    - gcloud auth activate-service-account --key-file /gcloud-service-key.json
    - gcloud config set project $PROJECT_ID
    - gcloud config set container/cluster clubfinity-cluster
    - gcloud config set compute/zone us-east1
    - gcloud container clusters get-credentials clubfinity-cluster --zone $ZONE
    - cat docker/deployment.yml | envsubst | kubectl apply -f -
  only:
    - master
