stages:
  - dependencies
  - test
  - build
  - staging
  - prod

install dependencies:
  stage: dependencies
  image: node:12
  cache:
    key:
      files:
        - Backend/node_modules
        - Frontend/node_modules
    paths:
      - Backend/node_modules
      - Frontend/node_modules
  script:
    - cd Backend
    - npm ci
    - cd ../Frontend
    - npm ci
  only:
    refs:
      - master
      - merge_requests
    changes:
      - Backend/package-lock.json
      - Frontend/package-lock.json

unit:
  stage: test
  image: node:12
  cache:
    key:
      files:
        - package.json
    paths:
      - Backend/node_modules
    policy: pull
  services:
    - mongo
  script:
    - cd Backend
    - npm run test:ci
    - npm run lint
    - cd ../Frontend
    - npm run lint
  only:
    - master
    - merge_requests

build api:
  services:
    - docker:dind
  stage: build
  image: registry.gitlab.com/ufsec/clubfinity/build-push:latest
  cache:
    key:
      files:
        - package.json
    paths:
      - Backend/node_modules
    policy: pull
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $GCLOUD_SERVICE_KEY > /gcloud-service-key.json
    - cat /gcloud-service-key.json
    - /google-cloud-sdk/bin/gcloud auth activate-service-account --key-file /gcloud-service-key.json
    - docker login -u _json_key --password-stdin https://us.gcr.io < /gcloud-service-key.json
  script:
    - docker build Backend/ -t "gcr.io/$PROJECT_ID/clubfinity-api"
    - /google-cloud-sdk/bin/gcloud docker -- push "gcr.io/$PROJECT_ID/clubfinity-api"
  only:
    - master

deploy staging:
  image: 'google/cloud-sdk'
  stage: staging
  script:
    - echo $GCLOUD_SERVICE_KEY > /gcloud-service-key.json
    - gcloud auth activate-service-account --key-file /gcloud-service-key.json
    - gcloud container clusters get-credentials clubfinity-cluster --zone $ZONE --project $PROJECT_ID
    - kubectl rollout restart deployment/clubfinity-staging
  only:
    - master

deploy prod:
  image: 'google/cloud-sdk'
  stage: prod
  when: manual
  script:
    - echo $GCLOUD_SERVICE_KEY > /gcloud-service-key.json
    - gcloud auth activate-service-account --key-file /gcloud-service-key.json
    - gcloud container clusters get-credentials clubfinity-cluster --zone $ZONE --project $PROJECT_ID
    - kubectl rollout restart deployment/clubfinity-prod
  only:
    - master
