stages:
  - test
  - build-deploy

api unit:
  stage: test
  image: node:12
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - Backend/node_modules
  services:
    - mongo
  before_script:
    - cd Backend
    - npm install
    - cd ..
  script:
    - cd Backend
    - npm run test:ci
    - cd ..
  only:
    - master

deploy api:
  stage: build-deploy
  script:
    - echo "It works!"

